### ISSUE TITLE
About fine-tuneDasheng

### ISSUE THREAD

**Issue by rookie0607** [XiaoMi/dasheng#1]
Hi, this is a very nice work, i want to fine tune the Dasheng-0.6B, how do i do that？

**Comment by RicherMans** [comment]
Hey @rookie0607 ,
There is a simple example for ESC-50 on the[ Huggingface page](https://huggingface.co/mispeech/dasheng-base):

https://github.com/jimbozhang/hf_transformers_custom_model_dasheng/blob/main/example_finetune_esc50.ipynb


Hope it helps,
Heinrich

**Comment by jimbozhang** [comment]
@rookie0607 And you may want to check out the out-of-the-box model which has been fine-tuned by AudioSet, with 49.7 mAP: https://github.com/XiaoMi/dasheng?tab=readme-ov-file#is-there-an-audioset-finetuned-dasheng
