### ISSUE TITLE
How to use directly

### ISSUE THREAD

**Issue by Xhlkx** [XiaoMi/dasheng#5]
I want to use dasheng to do audio classification directly. How can I do it? What are the category labels?

**Comment by RicherMans** [comment]
Hey there thanks for the interest!
Unfortunately, Dasheng is just an encoder and has no decoder attached yet.

The good news is that, at least during my testing, there shouldn't be any common task where dasheng would not work.

Junbo wrote a nice tutorial howto finetune dasheng on e.g., ESC-50, which you can find [here](https://github.com/jimbozhang/hf_transformers_custom_model_dasheng/blob/main/example_finetune_esc50.ipynb).

For other cases just use our api and jointly finetune the model towards your target task.
We have also a finetuned version on Audioset ready, which can be found [here](https://github.com/XiaoMi/dasheng?tab=readme-ov-file#is-there-an-audioset-finetuned-dasheng)

Kind regards,
Heinrich

**Comment by Xhlkx** [comment]
OK, thank you very much
